CREATE TABLE "TaiKhoan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "username" varchar(255),
  "password" varchar(255),
  "id_role" int
);

CREATE TABLE "VaiTro" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "TenVaiTro" varchar(255),
  "mota" varchar(255)
);

CREATE TABLE "HocSinh" (
  "id" int PRIMARY KEY NOT NULL,
  "MaHS" varchar(255),
  "HoVaTen" varchar(255),
  "NgaySinh" date,
  "GioiTinh" varchar(10),
  "id_Lop" int NOT NULL,
  "id_school" int NOT NULL
);

CREATE TABLE "QuanTriTruong" (
  "id" int PRIMARY KEY NOT NULL,
  "MaQTV" varchar(255),
  "HoVaTen" varchar(255),
  "NgaySinh" date,
  "GioiTinh" varchar(10),
  "id_school" int NOT NULL
);

CREATE TABLE "Truong" (
  "id" int PRIMARY KEY NOT NULL,
  "name" varchar(255)
);

CREATE TABLE "PhuHuynh" (
  "id" int PRIMARY KEY NOT NULL,
  "MaPH" varchar(255),
  "HoVaTen" varchar(255),
  "id_HocSinh" int,
  "SDT" varchar(15),
  "email" varchar(255),
  "NgaySinh" date,
  "GioiTinh" varchar(10)
);

CREATE TABLE "Lop" (
  "id" int PRIMARY KEY NOT NULL,
  "TenLop" varchar(10),
  "id_ToHopMon" int,
  "id_GiaoVienChuNhiem" int
);

CREATE TABLE "MonHoc" (
  "id" int PRIMARY KEY NOT NULL,
  "TenMon" varchar(255),
  "SoTiet" int
);

CREATE TABLE "ToHopMon" (
  "id" int PRIMARY KEY NOT NULL,
  "TenToHop" varchar(255),
  "mota" varchar(255)
);

CREATE TABLE "ChiTiet_ToHopMon" (
  "subject_group_id" int,
  "subject_id" int,
  "Note" varchar(255),
  PRIMARY KEY ("subject_group_id", "subject_id")
);

CREATE TABLE "GiaoVien" (
  "id" int PRIMARY KEY NOT NULL,
  "HoVaTen" varchar(255),
  "NgaySinh" date,
  "GioiTinh" varchar(10),
  "ViTri" varchar(255),
  "SDT" varchar(15),
  "DiaChi" varchar(255),
  "email" varchar(255),
  "NgayThamGia" date,
  "id_truong" int NOT NULL
);

CREATE TABLE "BanGiamHieu" (
  "id" int PRIMARY KEY NOT NULL,
  "id_truong" int,
  "MaBGV" varchar(255),
  "HoVaTen" varchar(255),
  "NgaySinh" date,
  "GioiTinh" varchar(10),
  "SDT" varchar(15),
  "DiaChi" varchar(255),
  "email" varchar(255)
);

CREATE TABLE "BangPhanCongGiaoVien" (
  "id" int PRIMARY KEY NOT NULL,
  "id_GiaoVien" int,
  "id_MonHoc" int,
  "id_Lop" int,
  "KyHoc" varchar(10),
  "NamHoc" varchar(20),
  "NgayPhanCong" timestamp
);

CREATE TABLE "BangPhanCongGiaoVienChuNhiem" (
  "id" int PRIMARY KEY NOT NULL,
  "id_GiaoVien" int,
  "id_Lop" int,
  "NamHoc" varchar(20),
  "NgayPhanCong" timestamp
);

CREATE TABLE "DiemDanh" (
  "application_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int NOT NULL,
  "NgayNghi" date NOT NULL,
  "LyDo" varchar(255) NOT NULL,
  "TinhTrang" varchar(50),
  "NgayNop" timestamp DEFAULT (current_timestamp),
  "pproved_by" int
);

CREATE TABLE "DiemSo" (
  "id" int PRIMARY KEY NOT NULL,
  "id_HocSinh" int,
  "id_MonHoc" int,
  "HocKy" varchar(10),
  "NamHoc" varchar(20),
  "DiemThuongKy" decimal(4,2),
  "DiemGiuaKy" decimal(4,2),
  "DiemCuoiKy" decimal(4,2),
  "DiemTrungBinh" decimal(4,2)
);

CREATE TABLE "LichSuDiem" (
  "id" int PRIMARY KEY NOT NULL,
  "id_DiemSo" int,
  "LoaiDiem" varchar(50),
  "DiemCu" decimal(4,2),
  "DiemMoi" decimal(4,2),
  "NguoiSua" int,
  "ThoiGian" timestamp,
  "LyDo" text
);

CREATE TABLE "YeuCauSuaDiem" (
  "id" int PRIMARY KEY NOT NULL,
  "id_DiemSo" int,
  "id_GiaoVien" int,
  "NgayGui" timestamp,
  "LoaiDiem" varchar(50),
  "DiemCu" decimal(4,2),
  "DiemMoi" decimal(4,2),
  "LyDo" text,
  "TrangThai" varchar(20),
  "NguoiDuyet" int,
  "ThoiGianDuyet" timestamp
);

CREATE TABLE "NhanXetHocTap" (
  "id" int PRIMARY KEY NOT NULL,
  "id_HocSinh" int,
  "id_GiaoVien" int,
  "HocKy" varchar(10),
  "NamHoc" varchar(20),
  "NoiDung" text,
  "NgayTao" timestamp
);

CREATE TABLE "HanhKiem" (
  "id" int PRIMARY KEY NOT NULL,
  "id_HocSinh" int,
  "HocKy" varchar(10),
  "NamHoc" varchar(20),
  "LoaiHanhKiem" varchar(20),
  "NhanXet" text,
  "NguoiDanhGia" int,
  "NgayDanhGia" timestamp
);

CREATE TABLE "ThongBao" (
  "id" int PRIMARY KEY NOT NULL,
  "TieuDe" varchar(255),
  "NoiDung" text,
  "NguoiDang" int,
  "NgayDang" timestamp,
  "NgayCapNhat" timestamp
);

CREATE TABLE "ThanhToanHocPhi" (
  "id" int PRIMARY KEY NOT NULL,
  "id_HocSinh" int,
  "HocKy" varchar(10),
  "NamHoc" varchar(20),
  "CongNo" decimal(12,2),
  "TienDaNop" decimal(12,2),
  "NgayThanhToan" timestamp,
  "PhuongThuc" varchar(50),
  "TrangThai" varchar(20)
);

CREATE TABLE "BaiTap" (
  "id" int PRIMARY KEY NOT NULL,
  "TieuDe" varchar(255),
  "NoiDung" text,
  "id_MonHoc" int,
  "id_Lop" int,
  "id_GiaoVien" int,
  "NgayGiao" timestamp,
  "HanNop" timestamp,
  "File" varchar(255),
  "TrangThai" varchar(20)
);

CREATE TABLE "BaiNop" (
  "id" int PRIMARY KEY NOT NULL,
  "id_BaiTap" int,
  "id_HocSinh" int,
  "NgayNop" timestamp,
  "file_path" varchar(255),
  "DiemSo" decimal(4,2),
  "NhanXet" text,
  "NgayCham" timestamp,
  "TrangThai" varchar(20)
);

CREATE TABLE "ThoiKhoaBieu" (
  "id" int PRIMARY KEY NOT NULL,
  "id_Lop" int,
  "id_MonHoc" int,
  "id_GiaoVien" int,
  "Thu" varchar(10),
  "Tiet" int,
  "HocKy" varchar(10),
  "NamHoc" varchar(20)
);

CREATE TABLE "HocBa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_HocSinh" int,
  "id_Lop" int,
  "id_Truong" int,
  "NamHoc" varchar(20),
  "HocKy" varchar(10),
  "DiemTrungBinh" decimal(4,2),
  "HanhKiem" varchar(20),
  "NhanXet" text
);

ALTER TABLE "TaiKhoan" ADD FOREIGN KEY ("id_role") REFERENCES "VaiTro" ("id");

ALTER TABLE "HocSinh" ADD FOREIGN KEY ("id_Lop") REFERENCES "Lop" ("id");

ALTER TABLE "HocSinh" ADD FOREIGN KEY ("id_school") REFERENCES "Truong" ("id");

ALTER TABLE "QuaTriTruong" ADD FOREIGN KEY ("id_school") REFERENCES "Truong" ("id");

ALTER TABLE "HocSinh" ADD FOREIGN KEY ("id") REFERENCES "PhuHuynh" ("id_HocSinh");

ALTER TABLE "Lop" ADD FOREIGN KEY ("id_ToHopMon") REFERENCES "ToHopMon" ("id");

ALTER TABLE "Lop" ADD FOREIGN KEY ("id_GiaoVienChuNhiem") REFERENCES "GiaoVien" ("id");

ALTER TABLE "ChiTiet_ToHopMon" ADD FOREIGN KEY ("subject_group_id") REFERENCES "ToHopMon" ("id");

ALTER TABLE "ChiTiet_ToHopMon" ADD FOREIGN KEY ("subject_id") REFERENCES "MonHoc" ("id");

ALTER TABLE "GiaoVien" ADD FOREIGN KEY ("id_truong") REFERENCES "Truong" ("id");

ALTER TABLE "Truong" ADD FOREIGN KEY ("id") REFERENCES "BanGiamHieu" ("id_truong");

ALTER TABLE "BangPhanCongGiaoVien" ADD FOREIGN KEY ("id_GiaoVien") REFERENCES "GiaoVien" ("id");

ALTER TABLE "BangPhanCongGiaoVien" ADD FOREIGN KEY ("id_MonHoc") REFERENCES "MonHoc" ("id");

ALTER TABLE "BangPhanCongGiaoVien" ADD FOREIGN KEY ("id_Lop") REFERENCES "Lop" ("id");

ALTER TABLE "BangPhanCongGiaoVienChuNhiem" ADD FOREIGN KEY ("id_GiaoVien") REFERENCES "GiaoVien" ("id");

ALTER TABLE "BangPhanCongGiaoVienChuNhiem" ADD FOREIGN KEY ("id_Lop") REFERENCES "Lop" ("id");

ALTER TABLE "DiemDanh" ADD FOREIGN KEY ("student_id") REFERENCES "HocSinh" ("id");

ALTER TABLE "DiemDanh" ADD FOREIGN KEY ("pproved_by") REFERENCES "GiaoVien" ("id");

ALTER TABLE "DiemSo" ADD FOREIGN KEY ("id_HocSinh") REFERENCES "HocSinh" ("id");

ALTER TABLE "DiemSo" ADD FOREIGN KEY ("id_MonHoc") REFERENCES "MonHoc" ("id");

ALTER TABLE "LichSuDiem" ADD FOREIGN KEY ("id_DiemSo") REFERENCES "DiemSo" ("id");

ALTER TABLE "LichSuDiem" ADD FOREIGN KEY ("NguoiSua") REFERENCES "GiaoVien" ("id");

ALTER TABLE "YeuCauSuaDiem" ADD FOREIGN KEY ("id_DiemSo") REFERENCES "DiemSo" ("id");

ALTER TABLE "YeuCauSuaDiem" ADD FOREIGN KEY ("id_GiaoVien") REFERENCES "GiaoVien" ("id");

ALTER TABLE "YeuCauSuaDiem" ADD FOREIGN KEY ("NguoiDuyet") REFERENCES "BanGiamHieu" ("id");

ALTER TABLE "NhanXetHocTap" ADD FOREIGN KEY ("id_HocSinh") REFERENCES "HocSinh" ("id");

ALTER TABLE "NhanXetHocTap" ADD FOREIGN KEY ("id_GiaoVien") REFERENCES "GiaoVien" ("id");

ALTER TABLE "HanhKiem" ADD FOREIGN KEY ("id_HocSinh") REFERENCES "HocSinh" ("id");

ALTER TABLE "HanhKiem" ADD FOREIGN KEY ("NguoiDanhGia") REFERENCES "GiaoVien" ("id");

ALTER TABLE "ThongBao" ADD FOREIGN KEY ("NguoiDang") REFERENCES "BanGiamHieu" ("id");

ALTER TABLE "ThanhToanHocPhi" ADD FOREIGN KEY ("id_HocSinh") REFERENCES "HocSinh" ("id");

ALTER TABLE "BaiTap" ADD FOREIGN KEY ("id_MonHoc") REFERENCES "MonHoc" ("id");

ALTER TABLE "BaiTap" ADD FOREIGN KEY ("id_Lop") REFERENCES "Lop" ("id");

ALTER TABLE "BaiTap" ADD FOREIGN KEY ("id_GiaoVien") REFERENCES "GiaoVien" ("id");

ALTER TABLE "BaiNop" ADD FOREIGN KEY ("id_BaiTap") REFERENCES "BaiTap" ("id");

ALTER TABLE "BaiNop" ADD FOREIGN KEY ("id_HocSinh") REFERENCES "HocSinh" ("id");

ALTER TABLE "ThoiKhoaBieu" ADD FOREIGN KEY ("id_Lop") REFERENCES "Lop" ("id");

ALTER TABLE "ThoiKhoaBieu" ADD FOREIGN KEY ("id_MonHoc") REFERENCES "MonHoc" ("id");

ALTER TABLE "ThoiKhoaBieu" ADD FOREIGN KEY ("id_GiaoVien") REFERENCES "GiaoVien" ("id");

ALTER TABLE "HocBa" ADD FOREIGN KEY ("id_HocSinh") REFERENCES "HocSinh" ("id");

ALTER TABLE "HocBa" ADD FOREIGN KEY ("id_Lop") REFERENCES "Lop" ("id");

ALTER TABLE "HocBa" ADD FOREIGN KEY ("id_Truong") REFERENCES "Truong" ("id");
